### ISSUE TITLE
[MacOS-12.2.1][x86_64] make test_bootstrap Error

### ISSUE THREAD

**Issue by weixiankong** [iru-/nopforth#25]
Hello,  nopforth failed on MacOS

compile src/x86_64/Darwin.s failed
```
mkdir -p bin
cc -ggdb -Isrc -c -o bin/nop.o src/x86_64/Darwin.s
src/x86_64/Darwin.s:5:10: error: Could not find include file 'boot.s'

....
src/x86_64/Darwin.s:256:9: error: Could not find incbin file 'arch.ns'
.incbin "arch.ns"

```

after change that 2 lines to
```
.include "x86_64/boot.s"
.incbin "x86_64/arch.ns"
```
it compiles, but test failed
```
mkdir -p bin
cc -ggdb -Isrc -c -o bin/nop.o src/x86_64/Darwin.s
cc -ggdb -o bin/nop bin/nop.o 
/bin/sh: line 1: 10066 Done                    echo
     10067 Segmentation fault: 11  | bin/nop
make: *** [test_bootstrap] Error 139

```

**Comment by iru-** [comment]
Sorry for the long delay in responding.
This was messed up in the process of porting to arm64. The fixes seem straightforward, but I don't currently have an intel mac to try them out. Would you be able to test them?

**Comment by iru-** [comment]
> Sorry for the long delay in responding. This was messed up in the process of porting to arm64. The fixes seem straightforward, but I don't currently have an intel mac to try them out. Would you be able to test them?

This might not be needed, as I added a macOS github workflow.

**Comment by iru-** [comment]
@weixiankong could you please try the [issue-25](https://github.com/iru-/nopforth/tree/issue-25) branch and tell me if it works on your side?

**Comment by weixiankong** [comment]
> @weixiankong could you please try the [issue-25](https://github.com/iru-/nopforth/tree/issue-25) branch and tell me if it works on your side?

Yes, it is fixed on my intel MacOS. I can play with nopforth now (∩_∩)

**Comment by iru-** [comment]
> > @weixiankong could you please try the [issue-25](https://github.com/iru-/nopforth/tree/issue-25) branch and tell me if it works on your side?
> 
> Yes, it is fixed on my intel MacOS. I can play with nopforth now (∩_∩)

Great!
Thank you for opening the issue and testing. The changes have been merged to main, so you can use that branch now.
